### ISSUE TITLE
Remove fractionDigits from the examples

### ISSUE THREAD

**Issue by DmitryMK** [cdisc-org/DataExchange-DatasetJson#10]
I have created a [branch](https://github.com/cdisc-org/DataExchange-DatasetJson/tree/examplesUpdate) for examples update. There are 2 updates in it:

* Removed fractionDigits
* Removed cm_nice.json dataset

During the meeting we discussed that we also want to compress everything and replace float with decimal in SDTM.
We need to decided which variables to update in SDTM, as there might be cases when it should stay float.

And for the compression, we might want to update the current SDTM, and simply avoid any new lines (unless they are part of the values). JSON prettify tools are build in many editors. If we want to keep the current SDTM format and apply it to ADaM datasets, then we need to recreate these files, because updating it via replacements might be challenging for me.

**Comment by lexjansen** [comment]
Thanks. I would be in favor of having compression. We should probably also remove the split folder in SDTM.
A quick look in the data shows that probably the xxSTRESx variables need to stay float (or double!) in VS and LB.

**Comment by lexjansen** [comment]
These issues were resolved.
