### ISSUE TITLE
Revised Examples - targetDataType decimal

### ISSUE THREAD

**Issue by mhungria** [cdisc-org/DataExchange-DatasetJson#31]
Note the updated examples have targetDataTime="decimal" for all dataType="decimal" values. Was it intended that way?

**Comment by lexjansen** [comment]
Yes, that is intended. See Supported Column Data Type Combinations table specification: [https://wiki.cdisc.org/display/DSJSON1DOT1/Dataset-JSON+1.1](https://wiki.cdisc.org/display/DSJSON1DOT1/Dataset-JSON+1.1)

**Comment by mhungria** [comment]
I added a comment to the specs:
